openapi: 3.0.1
info:
  title: Lab Portal API
  version: v1
  description: REST API για τη διαχείριση λιστών εκκρεμοτήτων (Todo List) - Θέμα 2
paths:
  /signup:
    post:
      summary: Εγγραφή νέου χρήστη
      tags:
        - Auth
  /auth/login:
    post:
      summary: Login και λήψη JWT Token
      tags:
        - Auth
  /auth/logout:
    get:
      summary: Logout χρήστη
      tags:
        - Auth
  /todos:
    get:
      summary: Λίστα όλων των Todos και των Items τους
      tags:
        - Todos
    post:
      summary: Δημιουργία νέου Todo
      tags:
        - Todos
  /todos/{id}:
    get:
      summary: Προβολή συγκεκριμένου Todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Todos
    put:
      summary: Ενημέρωση Todo
      tags:
        - Todos
    delete:
      summary: Διαγραφή Todo και των περιεχομένων του
      tags:
        - Todos
  /todos/{id}/items:
    post:
      summary: Δημιουργία νέου Todo Item
      tags:
        - Items
  /todos/{id}/items/{iid}:
    get:
      summary: Προβολή συγκεκριμένου Item
      tags:
        - Items
    put:
      summary: Ενημέρωση Todo Item
      tags:
        - Items
    delete:
      summary: Διαγραφή Todo Item
      tags:
        - Items